#!/usr/bin/env node
// build.js — generates two artefacts needed for file:// (local) usage:
//
//   components-data.js   — window.COMPONENTS_DATA from components.json
//   sa-worker-bundle.js  — all worker deps concatenated into a Blob URL
//
// Run after any change to src/*.js, optimizer.js, sa-worker.js, or components.json:
//   node build.js
//
// The generated files are committed to the repo so that index.html works
// when opened directly from the file system without a web server.

const fs   = require('fs');
const path = require('path');

const ROOT = __dirname;

// ── 1. components-data.js ────────────────────────────────────────────────────

const json = fs.readFileSync(path.join(ROOT, 'components.json'), 'utf8');
fs.writeFileSync(
  path.join(ROOT, 'components-data.js'),
  `// Generated by build.js — do not edit directly.\nwindow.COMPONENTS_DATA = ${json};\n`
);
console.log('[build] components-data.js written');

// ── 2. sa-worker-bundle.js ───────────────────────────────────────────────────

// Files loaded by sa-worker.js via importScripts, in dependency order.
const WORKER_DEPS = [
  'src/constants.js',
  'src/optimizer/rotation.js',
  'src/optimizer/bus.js',
  'src/optimizer/placement.js',
  'src/optimizer/score.js',
  'src/optimizer/validate.js',
  'src/sa/shell.js',
  'src/sa/moves.js',
  'src/sa/clusters.js',
  'src/sa/greedy.js',
  'src/sa/annealer.js',
  'optimizer.js',
];

// Worker entry point: sa-worker.js with the importScripts call stripped
// (the deps are already inlined above).
const workerEntry = fs.readFileSync(path.join(ROOT, 'sa-worker.js'), 'utf8')
  .replace(/^importScripts\([^)]+\);?\s*/m, '');

const parts = WORKER_DEPS.map(f => {
  const src = fs.readFileSync(path.join(ROOT, f), 'utf8');
  return `// --- ${f} ---\n${src}`;
});
parts.push(`// --- sa-worker.js ---\n${workerEntry}`);

const bundleCode = parts.join('\n\n');

// JSON.stringify safely escapes the code so it can be embedded in a JS string
// literal — no issues with backticks, backslashes, or other special characters.
fs.writeFileSync(
  path.join(ROOT, 'sa-worker-bundle.js'),
  `// Generated by build.js — do not edit directly.\n` +
  `// Registers a Blob URL for the SA worker so the app works from file://.\n` +
  `window.SA_WORKER_BLOB_URL = URL.createObjectURL(\n` +
  `  new Blob([${JSON.stringify(bundleCode)}], { type: 'application/javascript' })\n` +
  `);\n`
);
console.log('[build] sa-worker-bundle.js written');
console.log('[build] done.');
